# 用于拆分

In [1]:
import numpy as np
import pandas as pd
import time
file_path = '../data/originData.csv'

In [ ]:
class stock_divide(object):
    def __init__(self):
        self.file_path = '../data/originData.csv'
    
    def get_colnames(self):
        """读取源文件第一行，获取所有列名"""
        self.colNames = pd.read_csv(file_path, nrows = 1).columns
    
    def getStcokList(self):
        """获取当日所有的股票代码，去除重复后以pickle形式保存(series)"""
        stockDf = pd.read_csv(self.file_path, usecols = ['tickerName'])
        self.stockList = stockDf['tickerName'].drop_duplicates() 
        self.stockList.to_pickle("../data/stockDivideData/uniqueStockList.pkl")

In [3]:
stockList = pd.read_pickle("../data/stockDivideData/uniqueStockList.pkl")
time_start0 = time.perf_counter()
reader = pd.read_csv(file_path, sep=',', chunksize=1000000)
print("Time spent for reading file is: %.4f ms" %((time.perf_counter() - time_start0)*1000))
for i, chunk in enumerate(reader):
    time_start1 = time.perf_counter()
    print("start... ", i)
    for stockCode in stockList[:100]:
        time_start = time.perf_counter()
        stockFilePath = "../data/stockDivideData/StockData/" + stockCode + ".csv"
        if(i==0):
            chunk[chunk['tickerName']==stockCode].to_csv(stockFilePath)
        else:
            chunk[chunk['tickerName']==stockCode].to_csv(stockFilePath, mode="a", header=False)
    print("***finish " , i, " th wrting, the length of chunk is: ", len(chunk))
    print("***Time spent for reading file is: %.4f ms" %((time.perf_counter() - time_start)*1000))
print("Complete writing! Total Time spent is: %.4f s!"%((time.perf_counter() - time_start0)))

Time spent for reading file is: 6.3329 ms
start...  0
***finish  0  th wrting, the length of chunk is:  1000000
***Time spent for reading file is: 66.4526 ms
start...  1
***finish  1  th wrting, the length of chunk is:  1000000
***Time spent for reading file is: 53.9818 ms
start...  2
***finish  2  th wrting, the length of chunk is:  1000000
***Time spent for reading file is: 55.7257 ms
start...  3
***finish  3  th wrting, the length of chunk is:  1000000
***Time spent for reading file is: 55.2832 ms
start...  4
***finish  4  th wrting, the length of chunk is:  1000000
***Time spent for reading file is: 93.3154 ms
start...  5
***finish  5  th wrting, the length of chunk is:  1000000
***Time spent for reading file is: 62.6722 ms
start...  6
***finish  6  th wrting, the length of chunk is:  1000000
***Time spent for reading file is: 56.5845 ms
start...  7
***finish  7  th wrting, the length of chunk is:  1000000
***Time spent for reading file is: 57.5519 ms
start...  8
***finish  8  th wrting, the length of chunk is:  1000000
***Time spent for reading file is: 57.1941 ms
start...  9
***finish  9  th wrting, the length of chunk is:  1000000
***Time spent for reading file is: 55.8610 ms
start...  10
***finish  10  th wrting, the length of chunk is:  1000000
***Time spent for reading file is: 55.0128 ms
start...  11
***finish  11  th wrting, the length of chunk is:  1000000
***Time spent for reading file is: 58.4600 ms
start...  12
***finish  12  th wrting, the length of chunk is:  1000000
***Time spent for reading file is: 55.9265 ms
start...  13
***finish  13  th wrting, the length of chunk is:  1000000
***Time spent for reading file is: 69.0651 ms
start...  14
***finish  14  th wrting, the length of chunk is:  1000000
***Time spent for reading file is: 56.7032 ms
start...  15
***finish  15  th wrting, the length of chunk is:  740339
***Time spent for reading file is: 43.6154 ms
Complete writing! Total Time spent is: 156.5596 s!

In [24]:
mydf = pd.read_csv(file_path, sep=',', nrows=100000)
mydf[mydf["tickerName"] == '000001.SZ']

,addrTag,askPrice1,askPrice2,askPrice3,askPrice4,askPrice5,askVolume1,askVolume2,askVolume3,askVolume4,...,status,tickerIndex,tickerName,totalAskQty,totalBidQty,tradingDay,turnover,volume,weightedAvgAskPrc,weightedAvgBidPrc
0,0,NaN,NaN,NaN,NaN,NaN,0,0,0,0,...,0,0,000001.SZ,0,0,20210706,0,0,NaN,NaN
5968,0,22.07,NaN,NaN,NaN,NaN,900,0,0,0,...,0,0,000001.SZ,0,0,20210706,0,0,NaN,NaN
5969,0,22.07,NaN,NaN,NaN,NaN,900,0,0,0,...,0,0,000001.SZ,0,0,20210706,0,0,NaN,NaN
14776,0,22.18,NaN,NaN,NaN,NaN,30600,6000,0,0,...,0,0,000001.SZ,0,0,20210706,0,0,NaN,NaN
19176,0,22.18,NaN,NaN,NaN,NaN,36100,1400,0,0,...,0,0,000001.SZ,0,0,20210706,0,0,NaN,NaN
21029,0,22.18,NaN,NaN,NaN,NaN,36200,2300,0,0,...,0,0,000001.SZ,0,0,20210706,0,0,NaN,NaN
22351,0,22.20,NaN,NaN,NaN,NaN,40800,5200,0,0,...,0,0,000001.SZ,0,0,20210706,0,0,NaN,NaN
23604,0,22.20,NaN,NaN,NaN,NaN,41400,4500,0,0,...,0,0,000001.SZ,0,0,20210706,0,0,NaN,NaN
24919,0,22.06,NaN,NaN,NaN,NaN,64200,3000,0,0,...,0,0,000001.SZ,0,0,20210706,0,0,NaN,NaN
26303,0,22.06,NaN,NaN,NaN,NaN,64800,2400,0,0,...,0,0,000001.SZ,0,0,20210706,0,0,NaN,NaN
27888,0,22.05,NaN,NaN,NaN,NaN,61100,200,0,0,...,0,0,000001.SZ,0,0,20210706,0,0,NaN,NaN
32792,0,22.05,NaN,NaN,NaN,NaN,61200,100,0,0,...,0,0,000001.SZ,0,0,20210706,0,0,NaN,NaN
34561,0,22.05,NaN,NaN,NaN,NaN,61300,2800,0,0,...,0,0,000001.SZ,0,0,20210706,0,0,NaN,NaN
38117,0,22.05,NaN,NaN,NaN,NaN,59700,6400,0,0,...,0,0,000001.SZ,0,0,20210706,0,0,NaN,NaN
39982,0,22.05,NaN,NaN,NaN,NaN,62100,4300,0,0,...,0,0,000001.SZ,0,0,20210706,0,0,NaN,NaN
41818,0,22.05,NaN,NaN,NaN,NaN,63100,3600,0,0,...,0,0,000001.SZ,0,0,20210706,0,0,NaN,NaN
43667,0,22.05,NaN,NaN,NaN,NaN,63200,3500,0,0,...,0,0,000001.SZ,0,0,20210706,0,0,NaN,NaN
45528,0,22.05,NaN,NaN,NaN,NaN,63200,3900,0,0,...,0,0,000001.SZ,0,0,20210706,0,0,NaN,NaN
47409,0,22.05,NaN,NaN,NaN,NaN,63400,3900,0,0,...,0,0,000001.SZ,0,0,20210706,0,0,NaN,NaN
54988,0,22.05,NaN,NaN,NaN,NaN,63400,4200,0,0,...,0,0,000001.SZ,0,0,20210706,0,0,NaN,NaN
56852,0,22.05,NaN,NaN,NaN,NaN,63400,4700,0,0,...,0,0,000001.SZ,0,0,20210706,0,0,NaN,NaN
58697,0,22.05,NaN,NaN,NaN,NaN,64100,5500,0,0,...,0,0,000001.SZ,0,0,20210706,0,0,NaN,NaN
60607,0,22.05,NaN,NaN,NaN,NaN,41400,29800,0,0,...,0,0,000001.SZ,0,0,20210706,0,0,NaN,NaN
62407,0,22.05,NaN,NaN,NaN,NaN,40500,32400,0,0,...,0,0,000001.SZ,0,0,20210706,0,0,NaN,NaN
64302,0,22.05,NaN,NaN,NaN,NaN,40500,32800,0,0,...,0,0,000001.SZ,0,0,20210706,0,0,NaN,NaN
66138,0,22.05,NaN,NaN,NaN,NaN,40500,34300,0,0,...,0,0,000001.SZ,0,0,20210706,0,0,NaN,NaN
67939,0,22.05,NaN,NaN,NaN,NaN,40500,34400,0,0,...,0,0,000001.SZ,0,0,20210706,0,0,NaN,NaN
69668,0,22.05,NaN,NaN,NaN,NaN,40900,34000,0,0,...,0,0,000001.SZ,0,0,20210706,0,0,NaN,NaN
71431,0,22.05,NaN,NaN,NaN,NaN,40900,34600,0,0,...,0,0,000001.SZ,0,0,20210706,0,0,NaN,NaN
73256,0,22.05,NaN,NaN,NaN,NaN,37200,38300,0,0,...,0,0,000001.SZ,0,0,20210706,0,0,NaN,NaN
74090,0,22.05,NaN,NaN,NaN,NaN,36700,38800,0,0,...,0,0,000001.SZ,0,0,20210706,0,0,NaN,NaN
75867,0,22.05,NaN,NaN,NaN,NaN,51700,25700,0,0,...,0,0,000001.SZ,0,0,20210706,0,0,NaN,NaN
77546,0,22.05,NaN,NaN,NaN,NaN,56000,21700,0,0,...,0,0,000001.SZ,0,0,20210706,0,0,NaN,NaN
79192,0,22.05,NaN,NaN,NaN,NaN,56700,21600,0,0,...,0,0,000001.SZ,0,0,20210706,0,0,NaN,NaN
80793,0,22.05,NaN,NaN,NaN,NaN,58700,21100,0,0,...,0,0,000001.SZ,0,0,20210706,0,0,NaN,NaN
82492,0,22.05,NaN,NaN,NaN,NaN,58700,22000,0,0,...,0,0,000001.SZ,0,0,20210706,0,0,NaN,NaN
84197,0,22.05,NaN,NaN,NaN,NaN,64600,16300,0,0,...,0,0,000001.SZ,0,0,20210706,0,0,NaN,NaN
85981,0,22.05,NaN,NaN,NaN,NaN,66200,14800,0,0,...,0,0,000001.SZ,0,0,20210706,0,0,NaN,NaN
87765,0,22.05,NaN,NaN,NaN,NaN,66600,33000,0,0,...,0,0,000001.SZ,0,0,20210706,0,0,NaN,NaN
89543,0,22.05,NaN,NaN,NaN,NaN,67000,43800,0,0,...,0,0,000001.SZ,0,0,20210706,0,0,NaN,NaN
91373,0,22.05,NaN,NaN,NaN,NaN,67000,48400,0,0,...,0,0,000001.SZ,0,0,20210706,0,0,NaN,NaN
93156,0,22.05,NaN,NaN,NaN,NaN,67000,49000,0,0,...,0,0,000001.SZ,0,0,20210706,0,0,NaN,NaN
95027,0,22.05,NaN,NaN,NaN,NaN,67400,49100,0,0,...,0,0,000001.SZ,0,0,20210706,0,0,NaN,NaN
96971,0,22.05,NaN,NaN,NaN,NaN,67400,51100,0,0,...,0,0,000001.SZ,0,0,20210706,0,0,NaN,NaN
98933,0,22.00,NaN,NaN,NaN,NaN,70000,0,0,0,...,0,0,000001.SZ,0,0,20210706,0,0,NaN,NaN

In [27]:
df.to_csv("../data/dataExample.csv")

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 45 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   addrTag            1000000 non-null  int64
 1   askPrice1          984910 non-null   float64
 2   askPrice2          838033 non-null   float64
 3   askPrice3          837467 non-null   float64
 4   askPrice4          836972 non-null   float64
 5   askPrice5          836489 non-null   float64
 6   askVolume1         1000000 non-null  int64
 7   askVolume2         1000000 non-null  int64
 8   askVolume3         1000000 non-null  int64
 9   askVolume4         1000000 non-null  int64
 10  askVolume5         1000000 non-null  int64
 11  bidPrice1          989494 non-null   float64
 12  bidPrice2          843094 non-null   float64
 13  bidPrice3          842985 non-null   float64
 14  bidPrice4          842587 non-null   float64
 15  bidPrice5          842208 non-null   float64
 16  bidVolume1         1000000 non-null  int64
 17  bidVolume2         1000000 non-null  int64
 18  bidVolume3         1000000 non-null  int64
 19  bidVolume4         1000000 non-null  int64
 20  bidVolume5         1000000 non-null  int64
 21  broker             1000000 non-null  int64
 22  clock              1000000 non-null  int64
 23  exchTime           1000000 non-null  int64
 24  exchTimeUnderMs    1000000 non-null  int64
 25  high               842086 non-null   float64
 26  iopv               1000000 non-null  int64
 27  last               842089 non-null   float64
 28  localTime          1000000 non-null  int64
 29  localTimeUnderMs   1000000 non-null  int64
 30  low                842086 non-null   float64
 31  numTrades          1000000 non-null  int64
 32  open               840291 non-null   float64
 33  phaseCode          0 non-null        float64
 34  preClosePrice      999997 non-null   float64
 35  status             1000000 non-null  int64
 36  tickerIndex        1000000 non-null  int64
 37  tickerName         1000000 non-null  object
 38  totalAskQty        1000000 non-null  int64
 39  totalBidQty        1000000 non-null  int64
 40  tradingDay         1000000 non-null  int64
 41  turnover           1000000 non-null  int64
 42  volume             1000000 non-null  int64
 43  weightedAvgAskPrc  838528 non-null   float64
 44  weightedAvgBidPrc  843112 non-null   float64
dtypes: float64(18), int64(26), object(1)
memory usage: 343.3+ MB